# Generated by Django 4.1.2 on 2023-12-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.TextField(default=False, max_length=255),
        ),
    ]
